### ISSUE TITLE
CC-ES requires a block data disk

### ISSUE THREAD

**Issue by DamaniN** [RichBrumpton/terraform-azure-rubrik-cloud-cluster#1]
As I read it this TF will not create any data disks for Cloud Cluster ES. CC-ES requires (1) 512 GiB data disk  for caching. Please update the variables.tf file to reflect this.

**Comment by RichBrumpton** [comment]
Thanks for calling that out, updated description with corrected guidance.

https://github.com/RichBrumpton/terraform-azure-rubrik-cloud-cluster/commit/68bf874080a00cbeb09cab3295f89db28a064e3c
